{{- if .Values.kargo.enabled }}
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: {{ .Values.name }}
  namespace: {{ include "kargo-loader.kargoProject" . }}
spec:
  interval: {{ .Values.kargo.warehouse.interval }}
  subscriptions:
    {{- range .Values.kargo.warehouse.images }}
    - image:
        repoURL: {{ .repoURL }}
        {{- if .imageSelectionStrategy }}
        imageSelectionStrategy: {{ .imageSelectionStrategy }}
        {{- if .constraint }}
        constraint: {{ .constraint }}
        {{- end }}
        {{- else }}
        tagSelectionStrategy: {{ .tagSelectionStrategy | default "SemVer" }}
        {{- if .allowTags }}
        allowTags: {{ .allowTags }}
        {{- end }}
        {{- end }}
    {{- end }}
    {{- if or .Values.valuesFile .Values.manifestsPath }}
    - git:
        repoURL: {{ .Values.gitRepo }}
        branch: main
        includePaths:
          {{- if .Values.valuesFile }}
          - {{ .Values.valuesFile }}
          {{- end }}
          {{- if .Values.manifestsPath }}
          - {{ .Values.manifestsPath }}
          {{- end }}
    {{- end }}
    {{- if .Values.kargo.warehouse.chart.repoURL }}
    - chart:
        repoURL: {{ .Values.kargo.warehouse.chart.repoURL }}
        {{- if .Values.kargo.warehouse.chart.name }}
        name: {{ .Values.kargo.warehouse.chart.name }}
        {{- end }}
        semverConstraint: {{ .Values.kargo.warehouse.chart.semverConstraint | quote }}
    {{- end }}
    {{- if .Values.kargo.warehouse.gitSource.repoURL }}
    - git:
        repoURL: {{ .Values.kargo.warehouse.gitSource.repoURL }}
        commitSelectionStrategy: SemVer
        semverConstraint: {{ .Values.kargo.warehouse.gitSource.semverConstraint | quote }}
    {{- end }}
{{- end }}
