{{- if .Values.kargo.enabled }}
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: {{ include "kargo-loader.kargoProject" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    link.argocd.argoproj.io/external-link: "https://kargo.tailc14988.ts.net/project//{{ include "kargo-loader.kargoProject" . }}"
{{- end }}
