name: argocd
namespace: argocd

gitRepo: https://github.com/rhoades-brown/argo-config.git
targetRevision: kargo-argocd-prod.01m13px0kvg9r64xwdg3wxmg2c.5586f8d

chart:
  repoURL: https://argoproj.github.io/argo-helm
  name: argo-cd
  version: 10.4.1

valuesFile: valuesfiles/argocd.yaml
manifestsPath: manifests/argocd

noFinalizer: true

kargo:
  enabled: true
  project: kargo-argocd
  autoPromotionEnabled: true
  warehouse:
    images: []
    chart:
      repoURL: https://argoproj.github.io/argo-helm
      name: argo-cd
      semverConstraint: ">=9.5.15"
  stage:
    imageUpdates: []
