name: cert-manager
namespace: cert-manager

gitRepo: https://github.com/rhoades-brown/argo-config.git
targetRevision: kargo-cert-manager-prod.01kx1xdhw2q2mxj0n8qv3c2b6k.593ee7d

chart:
  repoURL: https://charts.jetstack.io
  name: cert-manager
  version: v1.21.0

valuesFile: valuesfiles/cert-manager.yaml

kargo:
  enabled: true
  project: kargo-cert-manager
  autoPromotionEnabled: true
  warehouse:
    images: []
    chart:
      repoURL: https://charts.jetstack.io
      name: cert-manager
      semverConstraint: ">=1.19.0"
  stage:
    imageUpdates: []

