name: cert-manager
namespace: cert-manager

gitRepo: https://github.com/rhoades-brown/argo-config.git
targetRevision: kargo-cert-manager-prod.01kyq7qxsg5c6ns2wm5nhp9r41.90640db

chart:
  repoURL: https://charts.jetstack.io
  name: cert-manager
  version: v1.21.1

valuesFile: valuesfiles/cert-manager.yaml

kargo:
  enabled: true
  project: kargo-cert-manager
  autoPromotionEnabled: true
  warehouse:
    images: []
    chart:
      repoURL: https://charts.jetstack.io
      name: cert-manager
      semverConstraint: ">=1.19.0"
  stage:
    imageUpdates: []

