name: external-snapshotter
namespace: kube-system

gitRepo: https://github.com/rhoades-brown/argo-config.git
targetRevision: kargo-external-snapshotter-prod.01kp4tynm66x08ks5daj0dzaf5.82d37dd

gitSource:
  repoURL: https://github.com/kubernetes-csi/external-snapshotter.git
  path: client/config/crd
  targetRevision: v8.5.0

kargo:
  enabled: true
  project: kargo-external-snapshotter
  autoPromotionEnabled: true
  warehouse:
    images: []
    chart:
      repoURL: ""
      semverConstraint: ""
    gitSource:
      repoURL: https://github.com/kubernetes-csi/external-snapshotter.git
      semverConstraint: ">=8.0.0"
  stage:
    imageUpdates: []

