name: external-secrets
namespace: external-secrets

gitRepo: https://github.com/rhoades-brown/argo-config.git
targetRevision: kargo-external-secrets-prod.01kw22sfw51s4z5b8wekcevk8g.7f4772d

chart:
  repoURL: https://charts.external-secrets.io
  name: external-secrets
  version: 2.7.0

valuesFile: valuesfiles/external-secrets.yaml

extraSyncOptions:
  - ServerSideApply=true
  - RespectIgnoreDifferences=true

ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jsonPointers:
      - /webhooks/0/clientConfig/caBundle
      - /webhooks/1/clientConfig/caBundle
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jsonPointers:
      - /webhooks/0/clientConfig/caBundle
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
      - /spec/conversion/webhook/clientConfig/caBundle
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jsonPointers:
      - /webhooks/0/clientConfig/service/name
      - /webhooks/0/clientConfig/service/namespace
      - /webhooks/1/clientConfig/service/name
      - /webhooks/1/clientConfig/service/namespace
kargo:
  enabled: true
  project: kargo-external-secrets
  autoPromotionEnabled: true
  warehouse:
    images: []
    chart:
      repoURL: https://charts.external-secrets.io
      name: external-secrets
      semverConstraint: ">=1.0.0"
  stage:
    imageUpdates: []
