name: external-secrets
namespace: external-secrets

gitRepo: https://github.com/rhoades-brown/argo-config.git
targetRevision: main

chart:
  repoURL: https://charts.external-secrets.io
  name: external-secrets
  version: 1.0.0

valuesFile: valuesfiles/external-secrets.yaml

kargo:
  enabled: true
  project: kargo-external-secrets
  autoPromotionEnabled: true
  warehouse:
    images: []
    chart:
      repoURL: https://charts.external-secrets.io
      name: external-secrets
      semverConstraint: ">=1.0.0"
  stage:
    imageUpdates: []
