name: external-secrets
namespace: external-secrets

gitRepo: https://github.com/rhoades-brown/argo-config.git
targetRevision: kargo-external-secrets-prod.01ksypbpy3vceeq9tmqfcz6632.8ff26f0

chart:
  repoURL: https://charts.external-secrets.io
  name: external-secrets
  version: 2.5.0

valuesFile: valuesfiles/external-secrets.yaml

extraSyncOptions:
  - ServerSideApply=true

kargo:
  enabled: true
  project: kargo-external-secrets
  autoPromotionEnabled: true
  warehouse:
    images: []
    chart:
      repoURL: https://charts.external-secrets.io
      name: external-secrets
      semverConstraint: ">=1.0.0"
  stage:
    imageUpdates: []
