name: immich
namespace: immich

gitRepo: https://github.com/rhoades-brown/argo-config.git
targetRevision: kargo-immich-prod.01kwm1zqbnna1mb4xhcy2y9tss.6467b54

chart:
  repoURL: oci://ghcr.io/immich-app/immich-charts/immich
  version: 0.13.1

valuesFile: valuesfiles/immich.yaml
manifestsPath: manifests/immich

kargo:
  enabled: true
  project: kargo-immich
  autoPromotionEnabled: true
  warehouse:
    images:
      - repoURL: ghcr.io/immich-app/immich-server
        tagSelectionStrategy: SemVer
        allowTags: "^v[0-9]+\\.[0-9]+\\.[0-9]+$"
    chart:
      repoURL: oci://ghcr.io/immich-app/immich-charts/immich
      semverConstraint: ">=0.10.0"
  stage:
    imageUpdates:
      - key: image.tag
        image: ghcr.io/immich-app/immich-server
        file: valuesfiles/immich.yaml
      - key: controllers.main.containers.main.image.tag
        image: ghcr.io/immich-app/immich-server
        file: valuesfiles/immich.yaml

