name: kargo
namespace: kargo

gitRepo: https://github.com/rhoades-brown/kargo-config.git
targetRevision: kargo-kargo-prod.01m3mwp9w792nyzb2a1v1ygmj8.669eff8

chart:
  repoURL: oci://ghcr.io/akuity/kargo-charts/kargo
  name: kargo
  version: 1.11.5

valuesFile: valuesfiles/kargo.yaml
manifestsPath: manifests/kargo

kargo:
  enabled: true
  project: kargo-kargo
  autoPromotionEnabled: true
  warehouse:
    images: []
    chart:
      repoURL: oci://ghcr.io/akuity/kargo-charts/kargo
      semverConstraint: ">=1.9.0"
  stage:
    imageUpdates: []

