name: kargo
namespace: kargo

gitRepo: https://github.com/rhoades-brown/kargo-config.git
targetRevision: kargo-kargo-prod.01ksgp7e8363vms5t86h4x16fm.a61c1c1

chart:
  repoURL: oci://ghcr.io/akuity/kargo-charts/kargo
  name: kargo
  version: 1.10.4

valuesFile: valuesfiles/kargo.yaml
manifestsPath: manifests/kargo

kargo:
  enabled: true
  project: kargo-kargo
  autoPromotionEnabled: true
  warehouse:
    images: []
    chart:
      repoURL: oci://ghcr.io/akuity/kargo-charts/kargo
      semverConstraint: ">=1.9.0"
  stage:
    imageUpdates: []

