name: kargo
namespace: kargo

gitRepo: https://github.com/rhoades-brown/kargo-config.git
targetRevision: kargo-kargo-prod.01kyapbekdhy9bk49zn1k5v2x9.17ba7fd

chart:
  repoURL: oci://ghcr.io/akuity/kargo-charts/kargo
  name: kargo
  version: 1.11.0

valuesFile: valuesfiles/kargo.yaml
manifestsPath: manifests/kargo

kargo:
  enabled: true
  project: kargo-kargo
  autoPromotionEnabled: true
  warehouse:
    images: []
    chart:
      repoURL: oci://ghcr.io/akuity/kargo-charts/kargo
      semverConstraint: ">=1.9.0"
  stage:
    imageUpdates: []

