name: kube-prometheus-stack
namespace: kube-prometheus-stack

gitRepo: https://github.com/rhoades-brown/argo-config.git
targetRevision: kargo-kube-prometheus-stack-prod.01kqjbe8fqd3rzd5c8j519bq08.7ab8609

chart:
  repoURL: https://prometheus-community.github.io/helm-charts
  name: kube-prometheus-stack
  version: 84.5.0

valuesFile: valuesfiles/kube-prometheus-stack.yaml

managedNamespaceMetadata:
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged

extraSyncOptions:
  - ApplyOutOfSyncOnly=true
  - ServerSideApply=true
  - RespectIgnoreDifferences=true

ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
      - '.webhooks[]?.clientConfig.caBundle'
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jqPathExpressions:
      - '.webhooks[]?.clientConfig.caBundle'
  - group: batch
    kind: Job
    jqPathExpressions:
      - '.spec.template.spec.containers[]?.resources'
  - kind: Secret
    name: kube-prometheus-stack-grafana
    jqPathExpressions:
      - '.data["admin-password"]'

kargo:
  enabled: true
  project: kargo-kube-prometheus-stack
  autoPromotionEnabled: true
  warehouse:
    images: []
    chart:
      repoURL: https://prometheus-community.github.io/helm-charts
      name: kube-prometheus-stack
      semverConstraint: ">=82.0.0"
  stage:
    imageUpdates: []

