name: open-webui
namespace: open-webui

gitRepo: https://github.com/rhoades-brown/argo-config.git
targetRevision: kargo-open-webui-prod.01kzq3gwvjzgxsejdnx434tgg2.c63a316

chart:
  repoURL: https://helm.openwebui.com/
  name: open-webui
  version: 16.0.0

valuesFile: valuesfiles/open-webui.yaml
manifestsPath: manifests/open-webui

kargo:
  enabled: true
  project: kargo-open-webui
  autoPromotionEnabled: true
  warehouse:
    interval: 1h0m0s
    images:
      - repoURL: ghcr.io/open-webui/open-webui
        tagSelectionStrategy: SemVer
      - repoURL: docker.io/ollama/ollama
        tagSelectionStrategy: SemVer
        allowTagsRegex: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
    chart:
      repoURL: https://helm.openwebui.com/
      name: open-webui
      semverConstraint: ">=12.0.0"
  stage:
    imageUpdates:
      - key: ollama.image.tag
        image: docker.io/ollama/ollama
        file: valuesfiles/open-webui.yaml

