name: paperless-ngx
namespace: paperless-ngx

gitRepo: https://github.com/rhoades-brown/argo-config.git
targetRevision: kargo-paperless-ngx-prod.01kr7cy62edqxzbr9z9whs6j6y.9b81a07

helmPath: helm/paperless-ngx

kargo:
  enabled: true
  project: kargo-paperless-ngx
  autoPromotionEnabled: true
  warehouse:
    interval: 1h0m0s
    images:
      - repoURL: ghcr.io/paperless-ngx/paperless-ngx
        tagSelectionStrategy: SemVer
        allowTags: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
      - repoURL: docker.io/gotenberg/gotenberg
        tagSelectionStrategy: SemVer
        allowTags: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
      - repoURL: docker.io/bitnami/redis
        imageSelectionStrategy: Digest
        constraint: latest
      - repoURL: docker.io/apache/tika
        imageSelectionStrategy: Digest
        constraint: latest
    chart:
      repoURL: ""
      semverConstraint: ""
  stage:
    imageUpdates:
      - key: paperless.image.tag
        image: ghcr.io/paperless-ngx/paperless-ngx
        file: helm/paperless-ngx/values.yaml
      - key: gotenberg.image.tag
        image: docker.io/gotenberg/gotenberg
        file: helm/paperless-ngx/values.yaml
      - key: redis.image.tag
        image: docker.io/bitnami/redis
        file: helm/paperless-ngx/values.yaml
      - key: tika.image.tag
        image: docker.io/apache/tika
        file: helm/paperless-ngx/values.yaml

