name: stirling-pdf
namespace: stirlingpdf

gitRepo: https://github.com/rhoades-brown/argo-config.git
targetRevision: kargo-stirling-pdf-prod.01kr24fnj1rkys1cmqpzpg1464.8678e86

chart:
  repoURL: https://stirling-tools.github.io/Stirling-PDF-chart
  name: stirling-pdf-chart
  version: 3.1.0

valuesFile: valuesfiles/pdf.yaml

kargo:
  enabled: true
  project: kargo-stirling-pdf
  autoPromotionEnabled: true
  warehouse:
    images:
      - repoURL: docker.stirlingpdf.com/stirlingtools/stirling-pdf
        tagSelectionStrategy: SemVer
        allowTags: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
    chart:
      repoURL: https://stirling-tools.github.io/Stirling-PDF-chart
      name: stirling-pdf-chart
      semverConstraint: ">=3.0.0"
  stage:
    imageUpdates:
      - key: image.tag
        image: docker.stirlingpdf.com/stirlingtools/stirling-pdf
        file: valuesfiles/pdf.yaml

