name: transmission
namespace: transmission

gitRepo: https://github.com/rhoades-brown/argo-config.git
targetRevision: main

manifestsPath: manifests/transmission

kargo:
  enabled: true
  project: kargo-transmission
  autoPromotionEnabled: true
  warehouse:
    images:
      - repoURL: linuxserver/transmission
        tagSelectionStrategy: Lexicographic
        allowTags: "^version-.*"
    chart:
      repoURL: ""
      semverConstraint: ""
  stage:
    imageUpdates:
      - key: spec.template.spec.containers[0].image
        image: linuxserver/transmission
        file: manifests/transmission/deployment.yaml
        useFullImage: true

