name: whoami
namespace: whoami

gitRepo: https://github.com/rhoades-brown/argo-config.git
targetRevision: kargo-whoami-prod.01kn7zktb62hjgbzz4nqxcn0ew.741970e

helmPath: helm/whoami

valuesFile: valuesfiles/whoami.yaml

kargo:
  enabled: true
  project: kargo-whoami
  autoPromotionEnabled: true
  warehouse:
    interval: 1h0m0s
    images:
      - repoURL: docker.io/traefik/whoami
        tagSelectionStrategy: SemVer
        allowTags: "^v[0-9]+\\.[0-9]+\\.[0-9]+$"
    chart:
      repoURL: ""
      semverConstraint: ""
  stage:
    imageUpdates:
      - key: image.tag
        image: docker.io/traefik/whoami
        file: valuesfiles/whoami.yaml

