---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kargo-applicationset-patch
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - applicationsets
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kargo-applicationset-patch
subjects:
  - kind: ServiceAccount
    name: kargo-controller
    namespace: kargo
roleRef:
  kind: ClusterRole
  name: kargo-applicationset-patch
  apiGroup: rbac.authorization.k8s.io
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: kargo-controller-token
#  namespace: kargo
#  annotations:
#    kubernetes.io/service-account.name: kargo-controller
#type: kubernetes.io/service-account-token
