---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kargo-git-repo-creds
  namespace: kargo-shared-resources
spec:
  secretStoreRef:
    name: pulumi-secret-store
    kind: ClusterSecretStore
  target:
    name: kargo-git-repo-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          kargo.akuity.io/cred-type: git
      type: Opaque
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        repoURL: "{{ .repoURL }}"
        repoURLIsRegex: "true"
  data:
    - secretKey: username
      remoteRef:
        key: repocreds.username
    - secretKey: password
      remoteRef:
        key: repocreds.password
    - secretKey: repoURL
      remoteRef:
        key: repocreds.url
